#ifndef DNN_CONFIG_HPP_
#define DNN_CONFIG_HPP_

#define FLOAT                                                                 0

#define INPUT_MEM_WIDTH                                                       64
#define OUTPUT_MEM_WIDTH                                                      64
#define INPUT_DIM                                                             128
#define INPUT_CH                                                              18
#define INPUT_BITS                                                            8
#define INPUT_INT_BITS                                                        1
typedef ap_fixed<INPUT_BITS,INPUT_INT_BITS,AP_RND_ZERO,AP_WRAP> INPUT_dtype;

#define CONV_BN_RELU_0_K                                                      3
#define CONV_BN_RELU_0_IFM_CH                                                 18
#define CONV_BN_RELU_0_IFM_DIM                                                128
#define CONV_BN_RELU_0_OFM_CH                                                 16
#define CONV_BN_RELU_0_OFM_DIM                                                128
#define CONV_BN_RELU_0_GROUPS                                                 1
#define CONV_BN_RELU_0_STRIDE                                                 1
#define CONV_BN_RELU_0_PADDING                                                1
#define CONV_BN_RELU_0_SIMD                                                   1
#define CONV_BN_RELU_0_PE                                                     1
#define CONV_BN_RELU_0_IFM_BITS                                               8
#define CONV_BN_RELU_0_IFM_INT_BITS                                           1
#define CONV_BN_RELU_0_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_0_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_0_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_0_INPUT_ACCESSESS                                        294912
#define CONV_BN_RELU_0_WEIGHT_BITS                                            8
#define CONV_BN_RELU_0_WEIGHT_INT_BITS                                        -2
#define CONV_BN_RELU_0_WEIGHT_SIMD_WIDTH                                      8
#define CONV_BN_RELU_0_WEIGHT_SIMD_PE_WIDTH                                   8
#define CONV_BN_RELU_0_BIAS_BITS                                              8
#define CONV_BN_RELU_0_BIAS_INT_BITS                                          -9
#define CONV_BN_RELU_0_ACC_BITS                                               32
#define CONV_BN_RELU_0_ACC_INT_BITS                                           16
#define CONV_BN_RELU_0_ATILES                                                 16
#define CONV_BN_RELU_0_WTILES                                                 2592
#define CONV_BN_RELU_0_SCALE_BITS                                             32
#define CONV_BN_RELU_0_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_0_SHIFT_BITS                                             32
#define CONV_BN_RELU_0_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_0_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_0_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_0_OFM_BITS                                               8
#define CONV_BN_RELU_0_OFM_INT_BITS                                           1
#define CONV_BN_RELU_0_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_0_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_0_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_0_OUPUT_ACCESSESS                                        262144
typedef ap_fixed<CONV_BN_RELU_0_IFM_BITS,CONV_BN_RELU_0_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_input_dtype;
typedef ap_fixed<CONV_BN_RELU_0_WEIGHT_BITS,CONV_BN_RELU_0_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_0_BIAS_BITS,CONV_BN_RELU_0_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_0_ACC_BITS,CONV_BN_RELU_0_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_0_SCALE_BITS,CONV_BN_RELU_0_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_0_SHIFT_BITS,CONV_BN_RELU_0_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_0_NORM_ACC_BITS,CONV_BN_RELU_0_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_0_OFM_BITS,CONV_BN_RELU_0_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_0_output_dtype;

#define CONV_BN_RELU_1_K                                                      3
#define CONV_BN_RELU_1_IFM_CH                                                 16
#define CONV_BN_RELU_1_IFM_DIM                                                128
#define CONV_BN_RELU_1_OFM_CH                                                 16
#define CONV_BN_RELU_1_OFM_DIM                                                128
#define CONV_BN_RELU_1_GROUPS                                                 1
#define CONV_BN_RELU_1_STRIDE                                                 1
#define CONV_BN_RELU_1_PADDING                                                1
#define CONV_BN_RELU_1_SIMD                                                   1
#define CONV_BN_RELU_1_PE                                                     1
#define CONV_BN_RELU_1_IFM_BITS                                               8
#define CONV_BN_RELU_1_IFM_INT_BITS                                           1
#define CONV_BN_RELU_1_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_1_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_1_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_1_INPUT_ACCESSESS                                        262144
#define CONV_BN_RELU_1_WEIGHT_BITS                                            8
#define CONV_BN_RELU_1_WEIGHT_INT_BITS                                        -2
#define CONV_BN_RELU_1_WEIGHT_SIMD_WIDTH                                      8
#define CONV_BN_RELU_1_WEIGHT_SIMD_PE_WIDTH                                   8
#define CONV_BN_RELU_1_BIAS_BITS                                              8
#define CONV_BN_RELU_1_BIAS_INT_BITS                                          -9
#define CONV_BN_RELU_1_ACC_BITS                                               32
#define CONV_BN_RELU_1_ACC_INT_BITS                                           16
#define CONV_BN_RELU_1_ATILES                                                 16
#define CONV_BN_RELU_1_WTILES                                                 2304
#define CONV_BN_RELU_1_SCALE_BITS                                             32
#define CONV_BN_RELU_1_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_1_SHIFT_BITS                                             32
#define CONV_BN_RELU_1_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_1_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_1_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_1_OFM_BITS                                               8
#define CONV_BN_RELU_1_OFM_INT_BITS                                           1
#define CONV_BN_RELU_1_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_1_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_1_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_1_OUPUT_ACCESSESS                                        262144
typedef ap_fixed<CONV_BN_RELU_1_IFM_BITS,CONV_BN_RELU_1_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_input_dtype;
typedef ap_fixed<CONV_BN_RELU_1_WEIGHT_BITS,CONV_BN_RELU_1_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_1_BIAS_BITS,CONV_BN_RELU_1_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_1_ACC_BITS,CONV_BN_RELU_1_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_1_SCALE_BITS,CONV_BN_RELU_1_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_1_SHIFT_BITS,CONV_BN_RELU_1_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_1_NORM_ACC_BITS,CONV_BN_RELU_1_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_1_OFM_BITS,CONV_BN_RELU_1_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_1_output_dtype;

#define SPLIT_0_SIMD                                                          1
#define SPLIT_0_PE                                                            1
#define SPLIT_0_IFM_BITS                                                      8
#define SPLIT_0_IFM_INT_BITS                                                  1
#define SPLIT_0_IFM_BITS_ALIGNED                                              8
#define SPLIT_0_INPUT_STREAM_WIDTH                                            8
#define SPLIT_0_INPUT_MEM_WIDTH                                               8
#define SPLIT_0_INPUT_ACCESSESS                                               262144
#define SPLIT_0_OFM_BITS                                                      8
#define SPLIT_0_OFM_INT_BITS                                                  1
#define SPLIT_0_OFM_BITS_ALIGNED                                              8
#define SPLIT_0_OUTPUT_STREAM_WIDTH                                           8
#define SPLIT_0_OUTPUT_MEM_WIDTH                                              8
#define SPLIT_0_OUPUT_ACCESSESS                                               262144
typedef ap_fixed<SPLIT_0_IFM_BITS,SPLIT_0_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> split_0_input_dtype;
typedef ap_fixed<SPLIT_0_OFM_BITS,SPLIT_0_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> split_0_output_dtype;

#define MAXPOOL_0_SIMD                                                        1
#define MAXPOOL_0_PE                                                          1
#define MAXPOOL_0_K                                                           2
#define MAXPOOL_0_STRIDE                                                      2
#define MAXPOOL_0_IFM_CH                                                      16
#define MAXPOOL_0_IFM_DIM                                                     128
#define MAXPOOL_0_OFM_CH                                                      16
#define MAXPOOL_0_OFM_DIM                                                     64
#define MAXPOOL_0_IFM_BITS                                                    8
#define MAXPOOL_0_IFM_INT_BITS                                                1
#define MAXPOOL_0_IFM_BITS_ALIGNED                                            8
#define MAXPOOL_0_INPUT_STREAM_WIDTH                                          8
#define MAXPOOL_0_INPUT_MEM_WIDTH                                             8
#define MAXPOOL_0_INPUT_ACCESSESS                                             262144
#define MAXPOOL_0_OFM_BITS                                                    8
#define MAXPOOL_0_OFM_INT_BITS                                                1
#define MAXPOOL_0_OFM_BITS_ALIGNED                                            8
#define MAXPOOL_0_OUTPUT_STREAM_WIDTH                                         8
#define MAXPOOL_0_OUTPUT_MEM_WIDTH                                            8
#define MAXPOOL_0_OUPUT_ACCESSESS                                             65536
typedef ap_fixed<MAXPOOL_0_IFM_BITS,MAXPOOL_0_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> maxpool_0_input_dtype;
typedef ap_fixed<MAXPOOL_0_OFM_BITS,MAXPOOL_0_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> maxpool_0_output_dtype;

#define CONV_BN_RELU_2_K                                                      3
#define CONV_BN_RELU_2_IFM_CH                                                 16
#define CONV_BN_RELU_2_IFM_DIM                                                64
#define CONV_BN_RELU_2_OFM_CH                                                 32
#define CONV_BN_RELU_2_OFM_DIM                                                64
#define CONV_BN_RELU_2_GROUPS                                                 1
#define CONV_BN_RELU_2_STRIDE                                                 1
#define CONV_BN_RELU_2_PADDING                                                1
#define CONV_BN_RELU_2_SIMD                                                   1
#define CONV_BN_RELU_2_PE                                                     1
#define CONV_BN_RELU_2_IFM_BITS                                               8
#define CONV_BN_RELU_2_IFM_INT_BITS                                           1
#define CONV_BN_RELU_2_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_2_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_2_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_2_INPUT_ACCESSESS                                        65536
#define CONV_BN_RELU_2_WEIGHT_BITS                                            7
#define CONV_BN_RELU_2_WEIGHT_INT_BITS                                        0
#define CONV_BN_RELU_2_WEIGHT_SIMD_WIDTH                                      7
#define CONV_BN_RELU_2_WEIGHT_SIMD_PE_WIDTH                                   7
#define CONV_BN_RELU_2_BIAS_BITS                                              8
#define CONV_BN_RELU_2_BIAS_INT_BITS                                          -6
#define CONV_BN_RELU_2_ACC_BITS                                               32
#define CONV_BN_RELU_2_ACC_INT_BITS                                           16
#define CONV_BN_RELU_2_ATILES                                                 32
#define CONV_BN_RELU_2_WTILES                                                 4608
#define CONV_BN_RELU_2_SCALE_BITS                                             32
#define CONV_BN_RELU_2_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_2_SHIFT_BITS                                             32
#define CONV_BN_RELU_2_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_2_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_2_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_2_OFM_BITS                                               8
#define CONV_BN_RELU_2_OFM_INT_BITS                                           1
#define CONV_BN_RELU_2_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_2_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_2_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_2_OUPUT_ACCESSESS                                        131072
typedef ap_fixed<CONV_BN_RELU_2_IFM_BITS,CONV_BN_RELU_2_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_input_dtype;
typedef ap_fixed<CONV_BN_RELU_2_WEIGHT_BITS,CONV_BN_RELU_2_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_2_BIAS_BITS,CONV_BN_RELU_2_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_2_ACC_BITS,CONV_BN_RELU_2_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_2_SCALE_BITS,CONV_BN_RELU_2_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_2_SHIFT_BITS,CONV_BN_RELU_2_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_2_NORM_ACC_BITS,CONV_BN_RELU_2_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_2_OFM_BITS,CONV_BN_RELU_2_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_2_output_dtype;

#define CONV_BN_RELU_3_K                                                      3
#define CONV_BN_RELU_3_IFM_CH                                                 32
#define CONV_BN_RELU_3_IFM_DIM                                                64
#define CONV_BN_RELU_3_OFM_CH                                                 32
#define CONV_BN_RELU_3_OFM_DIM                                                64
#define CONV_BN_RELU_3_GROUPS                                                 1
#define CONV_BN_RELU_3_STRIDE                                                 1
#define CONV_BN_RELU_3_PADDING                                                1
#define CONV_BN_RELU_3_SIMD                                                   1
#define CONV_BN_RELU_3_PE                                                     1
#define CONV_BN_RELU_3_IFM_BITS                                               8
#define CONV_BN_RELU_3_IFM_INT_BITS                                           1
#define CONV_BN_RELU_3_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_3_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_3_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_3_INPUT_ACCESSESS                                        131072
#define CONV_BN_RELU_3_WEIGHT_BITS                                            8
#define CONV_BN_RELU_3_WEIGHT_INT_BITS                                        -3
#define CONV_BN_RELU_3_WEIGHT_SIMD_WIDTH                                      8
#define CONV_BN_RELU_3_WEIGHT_SIMD_PE_WIDTH                                   8
#define CONV_BN_RELU_3_BIAS_BITS                                              8
#define CONV_BN_RELU_3_BIAS_INT_BITS                                          -10
#define CONV_BN_RELU_3_ACC_BITS                                               32
#define CONV_BN_RELU_3_ACC_INT_BITS                                           16
#define CONV_BN_RELU_3_ATILES                                                 32
#define CONV_BN_RELU_3_WTILES                                                 9216
#define CONV_BN_RELU_3_SCALE_BITS                                             32
#define CONV_BN_RELU_3_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_3_SHIFT_BITS                                             32
#define CONV_BN_RELU_3_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_3_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_3_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_3_OFM_BITS                                               8
#define CONV_BN_RELU_3_OFM_INT_BITS                                           1
#define CONV_BN_RELU_3_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_3_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_3_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_3_OUPUT_ACCESSESS                                        131072
typedef ap_fixed<CONV_BN_RELU_3_IFM_BITS,CONV_BN_RELU_3_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_input_dtype;
typedef ap_fixed<CONV_BN_RELU_3_WEIGHT_BITS,CONV_BN_RELU_3_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_3_BIAS_BITS,CONV_BN_RELU_3_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_3_ACC_BITS,CONV_BN_RELU_3_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_3_SCALE_BITS,CONV_BN_RELU_3_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_3_SHIFT_BITS,CONV_BN_RELU_3_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_3_NORM_ACC_BITS,CONV_BN_RELU_3_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_3_OFM_BITS,CONV_BN_RELU_3_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_3_output_dtype;

#define SPLIT_1_SIMD                                                          1
#define SPLIT_1_PE                                                            1
#define SPLIT_1_IFM_BITS                                                      8
#define SPLIT_1_IFM_INT_BITS                                                  1
#define SPLIT_1_IFM_BITS_ALIGNED                                              8
#define SPLIT_1_INPUT_STREAM_WIDTH                                            8
#define SPLIT_1_INPUT_MEM_WIDTH                                               8
#define SPLIT_1_INPUT_ACCESSESS                                               131072
#define SPLIT_1_OFM_BITS                                                      8
#define SPLIT_1_OFM_INT_BITS                                                  1
#define SPLIT_1_OFM_BITS_ALIGNED                                              8
#define SPLIT_1_OUTPUT_STREAM_WIDTH                                           8
#define SPLIT_1_OUTPUT_MEM_WIDTH                                              8
#define SPLIT_1_OUPUT_ACCESSESS                                               131072
typedef ap_fixed<SPLIT_1_IFM_BITS,SPLIT_1_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> split_1_input_dtype;
typedef ap_fixed<SPLIT_1_OFM_BITS,SPLIT_1_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> split_1_output_dtype;

#define MAXPOOL_1_SIMD                                                        1
#define MAXPOOL_1_PE                                                          1
#define MAXPOOL_1_K                                                           2
#define MAXPOOL_1_STRIDE                                                      2
#define MAXPOOL_1_IFM_CH                                                      32
#define MAXPOOL_1_IFM_DIM                                                     64
#define MAXPOOL_1_OFM_CH                                                      32
#define MAXPOOL_1_OFM_DIM                                                     32
#define MAXPOOL_1_IFM_BITS                                                    8
#define MAXPOOL_1_IFM_INT_BITS                                                1
#define MAXPOOL_1_IFM_BITS_ALIGNED                                            8
#define MAXPOOL_1_INPUT_STREAM_WIDTH                                          8
#define MAXPOOL_1_INPUT_MEM_WIDTH                                             8
#define MAXPOOL_1_INPUT_ACCESSESS                                             131072
#define MAXPOOL_1_OFM_BITS                                                    8
#define MAXPOOL_1_OFM_INT_BITS                                                1
#define MAXPOOL_1_OFM_BITS_ALIGNED                                            8
#define MAXPOOL_1_OUTPUT_STREAM_WIDTH                                         8
#define MAXPOOL_1_OUTPUT_MEM_WIDTH                                            8
#define MAXPOOL_1_OUPUT_ACCESSESS                                             32768
typedef ap_fixed<MAXPOOL_1_IFM_BITS,MAXPOOL_1_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> maxpool_1_input_dtype;
typedef ap_fixed<MAXPOOL_1_OFM_BITS,MAXPOOL_1_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> maxpool_1_output_dtype;

#define CONV_BN_RELU_4_K                                                      3
#define CONV_BN_RELU_4_IFM_CH                                                 32
#define CONV_BN_RELU_4_IFM_DIM                                                32
#define CONV_BN_RELU_4_OFM_CH                                                 64
#define CONV_BN_RELU_4_OFM_DIM                                                32
#define CONV_BN_RELU_4_GROUPS                                                 1
#define CONV_BN_RELU_4_STRIDE                                                 1
#define CONV_BN_RELU_4_PADDING                                                1
#define CONV_BN_RELU_4_SIMD                                                   1
#define CONV_BN_RELU_4_PE                                                     1
#define CONV_BN_RELU_4_IFM_BITS                                               8
#define CONV_BN_RELU_4_IFM_INT_BITS                                           1
#define CONV_BN_RELU_4_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_4_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_4_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_4_INPUT_ACCESSESS                                        32768
#define CONV_BN_RELU_4_WEIGHT_BITS                                            8
#define CONV_BN_RELU_4_WEIGHT_INT_BITS                                        0
#define CONV_BN_RELU_4_WEIGHT_SIMD_WIDTH                                      8
#define CONV_BN_RELU_4_WEIGHT_SIMD_PE_WIDTH                                   8
#define CONV_BN_RELU_4_BIAS_BITS                                              8
#define CONV_BN_RELU_4_BIAS_INT_BITS                                          -7
#define CONV_BN_RELU_4_ACC_BITS                                               32
#define CONV_BN_RELU_4_ACC_INT_BITS                                           16
#define CONV_BN_RELU_4_ATILES                                                 64
#define CONV_BN_RELU_4_WTILES                                                 18432
#define CONV_BN_RELU_4_SCALE_BITS                                             32
#define CONV_BN_RELU_4_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_4_SHIFT_BITS                                             32
#define CONV_BN_RELU_4_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_4_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_4_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_4_OFM_BITS                                               8
#define CONV_BN_RELU_4_OFM_INT_BITS                                           1
#define CONV_BN_RELU_4_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_4_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_4_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_4_OUPUT_ACCESSESS                                        65536
typedef ap_fixed<CONV_BN_RELU_4_IFM_BITS,CONV_BN_RELU_4_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_input_dtype;
typedef ap_fixed<CONV_BN_RELU_4_WEIGHT_BITS,CONV_BN_RELU_4_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_4_BIAS_BITS,CONV_BN_RELU_4_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_4_ACC_BITS,CONV_BN_RELU_4_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_4_SCALE_BITS,CONV_BN_RELU_4_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_4_SHIFT_BITS,CONV_BN_RELU_4_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_4_NORM_ACC_BITS,CONV_BN_RELU_4_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_4_OFM_BITS,CONV_BN_RELU_4_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_4_output_dtype;

#define CONV_BN_RELU_5_K                                                      3
#define CONV_BN_RELU_5_IFM_CH                                                 64
#define CONV_BN_RELU_5_IFM_DIM                                                32
#define CONV_BN_RELU_5_OFM_CH                                                 64
#define CONV_BN_RELU_5_OFM_DIM                                                32
#define CONV_BN_RELU_5_GROUPS                                                 1
#define CONV_BN_RELU_5_STRIDE                                                 1
#define CONV_BN_RELU_5_PADDING                                                1
#define CONV_BN_RELU_5_SIMD                                                   1
#define CONV_BN_RELU_5_PE                                                     1
#define CONV_BN_RELU_5_IFM_BITS                                               8
#define CONV_BN_RELU_5_IFM_INT_BITS                                           1
#define CONV_BN_RELU_5_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_5_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_5_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_5_INPUT_ACCESSESS                                        65536
#define CONV_BN_RELU_5_WEIGHT_BITS                                            8
#define CONV_BN_RELU_5_WEIGHT_INT_BITS                                        0
#define CONV_BN_RELU_5_WEIGHT_SIMD_WIDTH                                      8
#define CONV_BN_RELU_5_WEIGHT_SIMD_PE_WIDTH                                   8
#define CONV_BN_RELU_5_BIAS_BITS                                              8
#define CONV_BN_RELU_5_BIAS_INT_BITS                                          -7
#define CONV_BN_RELU_5_ACC_BITS                                               32
#define CONV_BN_RELU_5_ACC_INT_BITS                                           16
#define CONV_BN_RELU_5_ATILES                                                 64
#define CONV_BN_RELU_5_WTILES                                                 36864
#define CONV_BN_RELU_5_SCALE_BITS                                             32
#define CONV_BN_RELU_5_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_5_SHIFT_BITS                                             32
#define CONV_BN_RELU_5_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_5_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_5_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_5_OFM_BITS                                               8
#define CONV_BN_RELU_5_OFM_INT_BITS                                           1
#define CONV_BN_RELU_5_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_5_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_5_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_5_OUPUT_ACCESSESS                                        65536
typedef ap_fixed<CONV_BN_RELU_5_IFM_BITS,CONV_BN_RELU_5_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_input_dtype;
typedef ap_fixed<CONV_BN_RELU_5_WEIGHT_BITS,CONV_BN_RELU_5_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_5_BIAS_BITS,CONV_BN_RELU_5_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_5_ACC_BITS,CONV_BN_RELU_5_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_5_SCALE_BITS,CONV_BN_RELU_5_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_5_SHIFT_BITS,CONV_BN_RELU_5_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_5_NORM_ACC_BITS,CONV_BN_RELU_5_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_5_OFM_BITS,CONV_BN_RELU_5_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_5_output_dtype;

#define SPLIT_2_SIMD                                                          1
#define SPLIT_2_PE                                                            1
#define SPLIT_2_IFM_BITS                                                      8
#define SPLIT_2_IFM_INT_BITS                                                  1
#define SPLIT_2_IFM_BITS_ALIGNED                                              8
#define SPLIT_2_INPUT_STREAM_WIDTH                                            8
#define SPLIT_2_INPUT_MEM_WIDTH                                               8
#define SPLIT_2_INPUT_ACCESSESS                                               65536
#define SPLIT_2_OFM_BITS                                                      8
#define SPLIT_2_OFM_INT_BITS                                                  1
#define SPLIT_2_OFM_BITS_ALIGNED                                              8
#define SPLIT_2_OUTPUT_STREAM_WIDTH                                           8
#define SPLIT_2_OUTPUT_MEM_WIDTH                                              8
#define SPLIT_2_OUPUT_ACCESSESS                                               65536
typedef ap_fixed<SPLIT_2_IFM_BITS,SPLIT_2_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> split_2_input_dtype;
typedef ap_fixed<SPLIT_2_OFM_BITS,SPLIT_2_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> split_2_output_dtype;

#define MAXPOOL_2_SIMD                                                        1
#define MAXPOOL_2_PE                                                          1
#define MAXPOOL_2_K                                                           2
#define MAXPOOL_2_STRIDE                                                      2
#define MAXPOOL_2_IFM_CH                                                      64
#define MAXPOOL_2_IFM_DIM                                                     32
#define MAXPOOL_2_OFM_CH                                                      64
#define MAXPOOL_2_OFM_DIM                                                     16
#define MAXPOOL_2_IFM_BITS                                                    8
#define MAXPOOL_2_IFM_INT_BITS                                                1
#define MAXPOOL_2_IFM_BITS_ALIGNED                                            8
#define MAXPOOL_2_INPUT_STREAM_WIDTH                                          8
#define MAXPOOL_2_INPUT_MEM_WIDTH                                             8
#define MAXPOOL_2_INPUT_ACCESSESS                                             65536
#define MAXPOOL_2_OFM_BITS                                                    8
#define MAXPOOL_2_OFM_INT_BITS                                                1
#define MAXPOOL_2_OFM_BITS_ALIGNED                                            8
#define MAXPOOL_2_OUTPUT_STREAM_WIDTH                                         8
#define MAXPOOL_2_OUTPUT_MEM_WIDTH                                            8
#define MAXPOOL_2_OUPUT_ACCESSESS                                             16384
typedef ap_fixed<MAXPOOL_2_IFM_BITS,MAXPOOL_2_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> maxpool_2_input_dtype;
typedef ap_fixed<MAXPOOL_2_OFM_BITS,MAXPOOL_2_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> maxpool_2_output_dtype;

#define CONV_RELU_6_K                                                         3
#define CONV_RELU_6_IFM_CH                                                    64
#define CONV_RELU_6_IFM_DIM                                                   16
#define CONV_RELU_6_OFM_CH                                                    64
#define CONV_RELU_6_OFM_DIM                                                   16
#define CONV_RELU_6_GROUPS                                                    1
#define CONV_RELU_6_STRIDE                                                    1
#define CONV_RELU_6_PADDING                                                   1
#define CONV_RELU_6_SIMD                                                      1
#define CONV_RELU_6_PE                                                        1
#define CONV_RELU_6_IFM_BITS                                                  8
#define CONV_RELU_6_IFM_INT_BITS                                              1
#define CONV_RELU_6_IFM_BITS_ALIGNED                                          8
#define CONV_RELU_6_INPUT_STREAM_WIDTH                                        8
#define CONV_RELU_6_INPUT_MEM_WIDTH                                           8
#define CONV_RELU_6_INPUT_ACCESSESS                                           16384
#define CONV_RELU_6_WEIGHT_BITS                                               8
#define CONV_RELU_6_WEIGHT_INT_BITS                                           -3
#define CONV_RELU_6_WEIGHT_SIMD_WIDTH                                         8
#define CONV_RELU_6_WEIGHT_SIMD_PE_WIDTH                                      8
#define CONV_RELU_6_BIAS_BITS                                                 8
#define CONV_RELU_6_BIAS_INT_BITS                                             -10
#define CONV_RELU_6_ACC_BITS                                                  32
#define CONV_RELU_6_ACC_INT_BITS                                              16
#define CONV_RELU_6_ATILES                                                    64
#define CONV_RELU_6_WTILES                                                    36864
#define CONV_RELU_6_OFM_BITS                                                  8
#define CONV_RELU_6_OFM_INT_BITS                                              1
#define CONV_RELU_6_OFM_BITS_ALIGNED                                          8
#define CONV_RELU_6_OUTPUT_STREAM_WIDTH                                       8
#define CONV_RELU_6_OUTPUT_MEM_WIDTH                                          8
#define CONV_RELU_6_OUPUT_ACCESSESS                                           16384
typedef ap_fixed<CONV_RELU_6_IFM_BITS,CONV_RELU_6_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_6_input_dtype;
typedef ap_fixed<CONV_RELU_6_WEIGHT_BITS,CONV_RELU_6_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_6_weight_dtype;
typedef ap_fixed<CONV_RELU_6_BIAS_BITS,CONV_RELU_6_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_6_bias_dtype;
typedef ap_fixed<CONV_RELU_6_ACC_BITS,CONV_RELU_6_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_6_acc_dtype;
typedef ap_fixed<CONV_RELU_6_OFM_BITS,CONV_RELU_6_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_6_output_dtype;

#define CONV_RELU_7_K                                                         3
#define CONV_RELU_7_IFM_CH                                                    64
#define CONV_RELU_7_IFM_DIM                                                   16
#define CONV_RELU_7_OFM_CH                                                    64
#define CONV_RELU_7_OFM_DIM                                                   16
#define CONV_RELU_7_GROUPS                                                    1
#define CONV_RELU_7_STRIDE                                                    1
#define CONV_RELU_7_PADDING                                                   1
#define CONV_RELU_7_SIMD                                                      1
#define CONV_RELU_7_PE                                                        1
#define CONV_RELU_7_IFM_BITS                                                  8
#define CONV_RELU_7_IFM_INT_BITS                                              1
#define CONV_RELU_7_IFM_BITS_ALIGNED                                          8
#define CONV_RELU_7_INPUT_STREAM_WIDTH                                        8
#define CONV_RELU_7_INPUT_MEM_WIDTH                                           8
#define CONV_RELU_7_INPUT_ACCESSESS                                           16384
#define CONV_RELU_7_WEIGHT_BITS                                               8
#define CONV_RELU_7_WEIGHT_INT_BITS                                           -3
#define CONV_RELU_7_WEIGHT_SIMD_WIDTH                                         8
#define CONV_RELU_7_WEIGHT_SIMD_PE_WIDTH                                      8
#define CONV_RELU_7_BIAS_BITS                                                 8
#define CONV_RELU_7_BIAS_INT_BITS                                             -10
#define CONV_RELU_7_ACC_BITS                                                  32
#define CONV_RELU_7_ACC_INT_BITS                                              16
#define CONV_RELU_7_ATILES                                                    64
#define CONV_RELU_7_WTILES                                                    36864
#define CONV_RELU_7_OFM_BITS                                                  8
#define CONV_RELU_7_OFM_INT_BITS                                              1
#define CONV_RELU_7_OFM_BITS_ALIGNED                                          8
#define CONV_RELU_7_OUTPUT_STREAM_WIDTH                                       8
#define CONV_RELU_7_OUTPUT_MEM_WIDTH                                          8
#define CONV_RELU_7_OUPUT_ACCESSESS                                           16384
typedef ap_fixed<CONV_RELU_7_IFM_BITS,CONV_RELU_7_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_7_input_dtype;
typedef ap_fixed<CONV_RELU_7_WEIGHT_BITS,CONV_RELU_7_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_7_weight_dtype;
typedef ap_fixed<CONV_RELU_7_BIAS_BITS,CONV_RELU_7_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_7_bias_dtype;
typedef ap_fixed<CONV_RELU_7_ACC_BITS,CONV_RELU_7_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_7_acc_dtype;
typedef ap_fixed<CONV_RELU_7_OFM_BITS,CONV_RELU_7_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_relu_7_output_dtype;

#define CONVTRANSPOSE_RELU_8_K                                                2
#define CONVTRANSPOSE_RELU_8_IFM_CH                                           64
#define CONVTRANSPOSE_RELU_8_IFM_DIM                                          16
#define CONVTRANSPOSE_RELU_8_OFM_CH                                           64
#define CONVTRANSPOSE_RELU_8_OFM_DIM                                          32
#define CONVTRANSPOSE_RELU_8_GROUPS                                           1
#define CONVTRANSPOSE_RELU_8_STRIDE                                           2
#define CONVTRANSPOSE_RELU_8_PADDING                                          0
#define CONVTRANSPOSE_RELU_8_SIMD                                             1
#define CONVTRANSPOSE_RELU_8_PE                                               1
#define CONVTRANSPOSE_RELU_8_IFM_BITS                                         8
#define CONVTRANSPOSE_RELU_8_IFM_INT_BITS                                     1
#define CONVTRANSPOSE_RELU_8_IFM_BITS_ALIGNED                                 8
#define CONVTRANSPOSE_RELU_8_INPUT_STREAM_WIDTH                               8
#define CONVTRANSPOSE_RELU_8_INPUT_MEM_WIDTH                                  8
#define CONVTRANSPOSE_RELU_8_INPUT_ACCESSESS                                  16384
#define CONVTRANSPOSE_RELU_8_WEIGHT_BITS                                      8
#define CONVTRANSPOSE_RELU_8_WEIGHT_INT_BITS                                  -3
#define CONVTRANSPOSE_RELU_8_WEIGHT_SIMD_WIDTH                                8
#define CONVTRANSPOSE_RELU_8_WEIGHT_SIMD_PE_WIDTH                             8
#define CONVTRANSPOSE_RELU_8_BIAS_BITS                                        8
#define CONVTRANSPOSE_RELU_8_BIAS_INT_BITS                                    -10
#define CONVTRANSPOSE_RELU_8_ACC_BITS                                         32
#define CONVTRANSPOSE_RELU_8_ACC_INT_BITS                                     16
#define CONVTRANSPOSE_RELU_8_ATILES                                           64
#define CONVTRANSPOSE_RELU_8_WTILES                                           16384
#define CONVTRANSPOSE_RELU_8_OFM_BITS                                         8
#define CONVTRANSPOSE_RELU_8_OFM_INT_BITS                                     1
#define CONVTRANSPOSE_RELU_8_OFM_BITS_ALIGNED                                 8
#define CONVTRANSPOSE_RELU_8_OUTPUT_STREAM_WIDTH                              8
#define CONVTRANSPOSE_RELU_8_OUTPUT_MEM_WIDTH                                 8
#define CONVTRANSPOSE_RELU_8_OUPUT_ACCESSESS                                  65536
typedef ap_fixed<CONVTRANSPOSE_RELU_8_IFM_BITS,CONVTRANSPOSE_RELU_8_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_8_input_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_8_WEIGHT_BITS,CONVTRANSPOSE_RELU_8_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_8_weight_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_8_BIAS_BITS,CONVTRANSPOSE_RELU_8_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_8_bias_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_8_ACC_BITS,CONVTRANSPOSE_RELU_8_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_8_acc_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_8_OFM_BITS,CONVTRANSPOSE_RELU_8_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_8_output_dtype;

#define CONCAT_0_IFM_CH                                                       64
#define CONCAT_0_IFM_DIM                                                      32
#define CONCAT_0_IFM_BITS                                                     8
#define CONCAT_0_IFM_INT_BITS                                                 1
#define CONCAT_0_OFM_BITS                                                     8
#define CONCAT_0_OFM_INT_BITS                                                 1
#define CONCAT_0_INPUT_STREAM_WIDTH                                           8
#define CONCAT_0_OFM_BITS_ALIGNED                                             8
#define CONCAT_0_OUTPUT_STREAM_WIDTH                                          8
typedef ap_fixed<CONCAT_0_IFM_BITS,CONCAT_0_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_0_input_dtype;
typedef ap_fixed<CONCAT_0_OFM_BITS,CONCAT_0_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_0_output_dtype;
#define CONCAT_0_OUPUT_ACCESSESS                                              65536

#define CONV_BN_RELU_9_K                                                      3
#define CONV_BN_RELU_9_IFM_CH                                                 128
#define CONV_BN_RELU_9_IFM_DIM                                                32
#define CONV_BN_RELU_9_OFM_CH                                                 32
#define CONV_BN_RELU_9_OFM_DIM                                                32
#define CONV_BN_RELU_9_GROUPS                                                 1
#define CONV_BN_RELU_9_STRIDE                                                 1
#define CONV_BN_RELU_9_PADDING                                                1
#define CONV_BN_RELU_9_SIMD                                                   1
#define CONV_BN_RELU_9_PE                                                     1
#define CONV_BN_RELU_9_IFM_BITS                                               8
#define CONV_BN_RELU_9_IFM_INT_BITS                                           1
#define CONV_BN_RELU_9_IFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_9_INPUT_STREAM_WIDTH                                     8
#define CONV_BN_RELU_9_INPUT_MEM_WIDTH                                        8
#define CONV_BN_RELU_9_INPUT_ACCESSESS                                        131072
#define CONV_BN_RELU_9_WEIGHT_BITS                                            8
#define CONV_BN_RELU_9_WEIGHT_INT_BITS                                        -4
#define CONV_BN_RELU_9_WEIGHT_SIMD_WIDTH                                      8
#define CONV_BN_RELU_9_WEIGHT_SIMD_PE_WIDTH                                   8
#define CONV_BN_RELU_9_BIAS_BITS                                              8
#define CONV_BN_RELU_9_BIAS_INT_BITS                                          -11
#define CONV_BN_RELU_9_ACC_BITS                                               32
#define CONV_BN_RELU_9_ACC_INT_BITS                                           16
#define CONV_BN_RELU_9_ATILES                                                 32
#define CONV_BN_RELU_9_WTILES                                                 36864
#define CONV_BN_RELU_9_SCALE_BITS                                             32
#define CONV_BN_RELU_9_SCALE_INT_BITS                                         16
#define CONV_BN_RELU_9_SHIFT_BITS                                             32
#define CONV_BN_RELU_9_SHIFT_INT_BITS                                         16
#define CONV_BN_RELU_9_NORM_ACC_BITS                                          32
#define CONV_BN_RELU_9_NORM_ACC_INT_BITS                                      16
#define CONV_BN_RELU_9_OFM_BITS                                               8
#define CONV_BN_RELU_9_OFM_INT_BITS                                           1
#define CONV_BN_RELU_9_OFM_BITS_ALIGNED                                       8
#define CONV_BN_RELU_9_OUTPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_9_OUTPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_9_OUPUT_ACCESSESS                                        32768
typedef ap_fixed<CONV_BN_RELU_9_IFM_BITS,CONV_BN_RELU_9_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_input_dtype;
typedef ap_fixed<CONV_BN_RELU_9_WEIGHT_BITS,CONV_BN_RELU_9_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_9_BIAS_BITS,CONV_BN_RELU_9_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_9_ACC_BITS,CONV_BN_RELU_9_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_9_SCALE_BITS,CONV_BN_RELU_9_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_9_SHIFT_BITS,CONV_BN_RELU_9_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_9_NORM_ACC_BITS,CONV_BN_RELU_9_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_9_OFM_BITS,CONV_BN_RELU_9_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_9_output_dtype;

#define CONV_BN_RELU_10_K                                                     3
#define CONV_BN_RELU_10_IFM_CH                                                32
#define CONV_BN_RELU_10_IFM_DIM                                               32
#define CONV_BN_RELU_10_OFM_CH                                                32
#define CONV_BN_RELU_10_OFM_DIM                                               32
#define CONV_BN_RELU_10_GROUPS                                                1
#define CONV_BN_RELU_10_STRIDE                                                1
#define CONV_BN_RELU_10_PADDING                                               1
#define CONV_BN_RELU_10_SIMD                                                  1
#define CONV_BN_RELU_10_PE                                                    1
#define CONV_BN_RELU_10_IFM_BITS                                              8
#define CONV_BN_RELU_10_IFM_INT_BITS                                          1
#define CONV_BN_RELU_10_IFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_10_INPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_10_INPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_10_INPUT_ACCESSESS                                       32768
#define CONV_BN_RELU_10_WEIGHT_BITS                                           8
#define CONV_BN_RELU_10_WEIGHT_INT_BITS                                       -3
#define CONV_BN_RELU_10_WEIGHT_SIMD_WIDTH                                     8
#define CONV_BN_RELU_10_WEIGHT_SIMD_PE_WIDTH                                  8
#define CONV_BN_RELU_10_BIAS_BITS                                             8
#define CONV_BN_RELU_10_BIAS_INT_BITS                                         -10
#define CONV_BN_RELU_10_ACC_BITS                                              32
#define CONV_BN_RELU_10_ACC_INT_BITS                                          16
#define CONV_BN_RELU_10_ATILES                                                32
#define CONV_BN_RELU_10_WTILES                                                9216
#define CONV_BN_RELU_10_SCALE_BITS                                            32
#define CONV_BN_RELU_10_SCALE_INT_BITS                                        16
#define CONV_BN_RELU_10_SHIFT_BITS                                            32
#define CONV_BN_RELU_10_SHIFT_INT_BITS                                        16
#define CONV_BN_RELU_10_NORM_ACC_BITS                                         32
#define CONV_BN_RELU_10_NORM_ACC_INT_BITS                                     16
#define CONV_BN_RELU_10_OFM_BITS                                              8
#define CONV_BN_RELU_10_OFM_INT_BITS                                          1
#define CONV_BN_RELU_10_OFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_10_OUTPUT_STREAM_WIDTH                                   8
#define CONV_BN_RELU_10_OUTPUT_MEM_WIDTH                                      8
#define CONV_BN_RELU_10_OUPUT_ACCESSESS                                       32768
typedef ap_fixed<CONV_BN_RELU_10_IFM_BITS,CONV_BN_RELU_10_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_input_dtype;
typedef ap_fixed<CONV_BN_RELU_10_WEIGHT_BITS,CONV_BN_RELU_10_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_10_BIAS_BITS,CONV_BN_RELU_10_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_10_ACC_BITS,CONV_BN_RELU_10_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_10_SCALE_BITS,CONV_BN_RELU_10_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_10_SHIFT_BITS,CONV_BN_RELU_10_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_10_NORM_ACC_BITS,CONV_BN_RELU_10_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_10_OFM_BITS,CONV_BN_RELU_10_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_10_output_dtype;

#define CONVTRANSPOSE_RELU_11_K                                               2
#define CONVTRANSPOSE_RELU_11_IFM_CH                                          32
#define CONVTRANSPOSE_RELU_11_IFM_DIM                                         32
#define CONVTRANSPOSE_RELU_11_OFM_CH                                          32
#define CONVTRANSPOSE_RELU_11_OFM_DIM                                         64
#define CONVTRANSPOSE_RELU_11_GROUPS                                          1
#define CONVTRANSPOSE_RELU_11_STRIDE                                          2
#define CONVTRANSPOSE_RELU_11_PADDING                                         0
#define CONVTRANSPOSE_RELU_11_SIMD                                            1
#define CONVTRANSPOSE_RELU_11_PE                                              1
#define CONVTRANSPOSE_RELU_11_IFM_BITS                                        8
#define CONVTRANSPOSE_RELU_11_IFM_INT_BITS                                    1
#define CONVTRANSPOSE_RELU_11_IFM_BITS_ALIGNED                                8
#define CONVTRANSPOSE_RELU_11_INPUT_STREAM_WIDTH                              8
#define CONVTRANSPOSE_RELU_11_INPUT_MEM_WIDTH                                 8
#define CONVTRANSPOSE_RELU_11_INPUT_ACCESSESS                                 32768
#define CONVTRANSPOSE_RELU_11_WEIGHT_BITS                                     8
#define CONVTRANSPOSE_RELU_11_WEIGHT_INT_BITS                                 -2
#define CONVTRANSPOSE_RELU_11_WEIGHT_SIMD_WIDTH                               8
#define CONVTRANSPOSE_RELU_11_WEIGHT_SIMD_PE_WIDTH                            8
#define CONVTRANSPOSE_RELU_11_BIAS_BITS                                       8
#define CONVTRANSPOSE_RELU_11_BIAS_INT_BITS                                   -9
#define CONVTRANSPOSE_RELU_11_ACC_BITS                                        32
#define CONVTRANSPOSE_RELU_11_ACC_INT_BITS                                    16
#define CONVTRANSPOSE_RELU_11_ATILES                                          32
#define CONVTRANSPOSE_RELU_11_WTILES                                          4096
#define CONVTRANSPOSE_RELU_11_OFM_BITS                                        8
#define CONVTRANSPOSE_RELU_11_OFM_INT_BITS                                    1
#define CONVTRANSPOSE_RELU_11_OFM_BITS_ALIGNED                                8
#define CONVTRANSPOSE_RELU_11_OUTPUT_STREAM_WIDTH                             8
#define CONVTRANSPOSE_RELU_11_OUTPUT_MEM_WIDTH                                8
#define CONVTRANSPOSE_RELU_11_OUPUT_ACCESSESS                                 131072
typedef ap_fixed<CONVTRANSPOSE_RELU_11_IFM_BITS,CONVTRANSPOSE_RELU_11_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_11_input_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_11_WEIGHT_BITS,CONVTRANSPOSE_RELU_11_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_11_weight_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_11_BIAS_BITS,CONVTRANSPOSE_RELU_11_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_11_bias_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_11_ACC_BITS,CONVTRANSPOSE_RELU_11_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_11_acc_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_11_OFM_BITS,CONVTRANSPOSE_RELU_11_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_11_output_dtype;

#define CONCAT_1_IFM_CH                                                       32
#define CONCAT_1_IFM_DIM                                                      64
#define CONCAT_1_IFM_BITS                                                     8
#define CONCAT_1_IFM_INT_BITS                                                 1
#define CONCAT_1_OFM_BITS                                                     8
#define CONCAT_1_OFM_INT_BITS                                                 1
#define CONCAT_1_INPUT_STREAM_WIDTH                                           8
#define CONCAT_1_OFM_BITS_ALIGNED                                             8
#define CONCAT_1_OUTPUT_STREAM_WIDTH                                          8
typedef ap_fixed<CONCAT_1_IFM_BITS,CONCAT_1_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_1_input_dtype;
typedef ap_fixed<CONCAT_1_OFM_BITS,CONCAT_1_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_1_output_dtype;
#define CONCAT_1_OUPUT_ACCESSESS                                              131072

#define CONV_BN_RELU_12_K                                                     3
#define CONV_BN_RELU_12_IFM_CH                                                64
#define CONV_BN_RELU_12_IFM_DIM                                               64
#define CONV_BN_RELU_12_OFM_CH                                                16
#define CONV_BN_RELU_12_OFM_DIM                                               64
#define CONV_BN_RELU_12_GROUPS                                                1
#define CONV_BN_RELU_12_STRIDE                                                1
#define CONV_BN_RELU_12_PADDING                                               1
#define CONV_BN_RELU_12_SIMD                                                  1
#define CONV_BN_RELU_12_PE                                                    1
#define CONV_BN_RELU_12_IFM_BITS                                              8
#define CONV_BN_RELU_12_IFM_INT_BITS                                          1
#define CONV_BN_RELU_12_IFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_12_INPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_12_INPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_12_INPUT_ACCESSESS                                       262144
#define CONV_BN_RELU_12_WEIGHT_BITS                                           8
#define CONV_BN_RELU_12_WEIGHT_INT_BITS                                       -3
#define CONV_BN_RELU_12_WEIGHT_SIMD_WIDTH                                     8
#define CONV_BN_RELU_12_WEIGHT_SIMD_PE_WIDTH                                  8
#define CONV_BN_RELU_12_BIAS_BITS                                             8
#define CONV_BN_RELU_12_BIAS_INT_BITS                                         -10
#define CONV_BN_RELU_12_ACC_BITS                                              32
#define CONV_BN_RELU_12_ACC_INT_BITS                                          16
#define CONV_BN_RELU_12_ATILES                                                16
#define CONV_BN_RELU_12_WTILES                                                9216
#define CONV_BN_RELU_12_SCALE_BITS                                            32
#define CONV_BN_RELU_12_SCALE_INT_BITS                                        16
#define CONV_BN_RELU_12_SHIFT_BITS                                            32
#define CONV_BN_RELU_12_SHIFT_INT_BITS                                        16
#define CONV_BN_RELU_12_NORM_ACC_BITS                                         32
#define CONV_BN_RELU_12_NORM_ACC_INT_BITS                                     16
#define CONV_BN_RELU_12_OFM_BITS                                              8
#define CONV_BN_RELU_12_OFM_INT_BITS                                          1
#define CONV_BN_RELU_12_OFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_12_OUTPUT_STREAM_WIDTH                                   8
#define CONV_BN_RELU_12_OUTPUT_MEM_WIDTH                                      8
#define CONV_BN_RELU_12_OUPUT_ACCESSESS                                       65536
typedef ap_fixed<CONV_BN_RELU_12_IFM_BITS,CONV_BN_RELU_12_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_input_dtype;
typedef ap_fixed<CONV_BN_RELU_12_WEIGHT_BITS,CONV_BN_RELU_12_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_12_BIAS_BITS,CONV_BN_RELU_12_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_12_ACC_BITS,CONV_BN_RELU_12_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_12_SCALE_BITS,CONV_BN_RELU_12_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_12_SHIFT_BITS,CONV_BN_RELU_12_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_12_NORM_ACC_BITS,CONV_BN_RELU_12_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_12_OFM_BITS,CONV_BN_RELU_12_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_12_output_dtype;

#define CONV_BN_RELU_13_K                                                     3
#define CONV_BN_RELU_13_IFM_CH                                                16
#define CONV_BN_RELU_13_IFM_DIM                                               64
#define CONV_BN_RELU_13_OFM_CH                                                16
#define CONV_BN_RELU_13_OFM_DIM                                               64
#define CONV_BN_RELU_13_GROUPS                                                1
#define CONV_BN_RELU_13_STRIDE                                                1
#define CONV_BN_RELU_13_PADDING                                               1
#define CONV_BN_RELU_13_SIMD                                                  1
#define CONV_BN_RELU_13_PE                                                    1
#define CONV_BN_RELU_13_IFM_BITS                                              8
#define CONV_BN_RELU_13_IFM_INT_BITS                                          1
#define CONV_BN_RELU_13_IFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_13_INPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_13_INPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_13_INPUT_ACCESSESS                                       65536
#define CONV_BN_RELU_13_WEIGHT_BITS                                           8
#define CONV_BN_RELU_13_WEIGHT_INT_BITS                                       -2
#define CONV_BN_RELU_13_WEIGHT_SIMD_WIDTH                                     8
#define CONV_BN_RELU_13_WEIGHT_SIMD_PE_WIDTH                                  8
#define CONV_BN_RELU_13_BIAS_BITS                                             8
#define CONV_BN_RELU_13_BIAS_INT_BITS                                         -9
#define CONV_BN_RELU_13_ACC_BITS                                              32
#define CONV_BN_RELU_13_ACC_INT_BITS                                          16
#define CONV_BN_RELU_13_ATILES                                                16
#define CONV_BN_RELU_13_WTILES                                                2304
#define CONV_BN_RELU_13_SCALE_BITS                                            32
#define CONV_BN_RELU_13_SCALE_INT_BITS                                        16
#define CONV_BN_RELU_13_SHIFT_BITS                                            32
#define CONV_BN_RELU_13_SHIFT_INT_BITS                                        16
#define CONV_BN_RELU_13_NORM_ACC_BITS                                         32
#define CONV_BN_RELU_13_NORM_ACC_INT_BITS                                     16
#define CONV_BN_RELU_13_OFM_BITS                                              8
#define CONV_BN_RELU_13_OFM_INT_BITS                                          1
#define CONV_BN_RELU_13_OFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_13_OUTPUT_STREAM_WIDTH                                   8
#define CONV_BN_RELU_13_OUTPUT_MEM_WIDTH                                      8
#define CONV_BN_RELU_13_OUPUT_ACCESSESS                                       65536
typedef ap_fixed<CONV_BN_RELU_13_IFM_BITS,CONV_BN_RELU_13_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_input_dtype;
typedef ap_fixed<CONV_BN_RELU_13_WEIGHT_BITS,CONV_BN_RELU_13_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_13_BIAS_BITS,CONV_BN_RELU_13_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_13_ACC_BITS,CONV_BN_RELU_13_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_13_SCALE_BITS,CONV_BN_RELU_13_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_13_SHIFT_BITS,CONV_BN_RELU_13_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_13_NORM_ACC_BITS,CONV_BN_RELU_13_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_13_OFM_BITS,CONV_BN_RELU_13_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_13_output_dtype;

#define CONVTRANSPOSE_RELU_14_K                                               2
#define CONVTRANSPOSE_RELU_14_IFM_CH                                          16
#define CONVTRANSPOSE_RELU_14_IFM_DIM                                         64
#define CONVTRANSPOSE_RELU_14_OFM_CH                                          16
#define CONVTRANSPOSE_RELU_14_OFM_DIM                                         128
#define CONVTRANSPOSE_RELU_14_GROUPS                                          1
#define CONVTRANSPOSE_RELU_14_STRIDE                                          2
#define CONVTRANSPOSE_RELU_14_PADDING                                         0
#define CONVTRANSPOSE_RELU_14_SIMD                                            1
#define CONVTRANSPOSE_RELU_14_PE                                              1
#define CONVTRANSPOSE_RELU_14_IFM_BITS                                        8
#define CONVTRANSPOSE_RELU_14_IFM_INT_BITS                                    1
#define CONVTRANSPOSE_RELU_14_IFM_BITS_ALIGNED                                8
#define CONVTRANSPOSE_RELU_14_INPUT_STREAM_WIDTH                              8
#define CONVTRANSPOSE_RELU_14_INPUT_MEM_WIDTH                                 8
#define CONVTRANSPOSE_RELU_14_INPUT_ACCESSESS                                 65536
#define CONVTRANSPOSE_RELU_14_WEIGHT_BITS                                     8
#define CONVTRANSPOSE_RELU_14_WEIGHT_INT_BITS                                 -2
#define CONVTRANSPOSE_RELU_14_WEIGHT_SIMD_WIDTH                               8
#define CONVTRANSPOSE_RELU_14_WEIGHT_SIMD_PE_WIDTH                            8
#define CONVTRANSPOSE_RELU_14_BIAS_BITS                                       8
#define CONVTRANSPOSE_RELU_14_BIAS_INT_BITS                                   -9
#define CONVTRANSPOSE_RELU_14_ACC_BITS                                        32
#define CONVTRANSPOSE_RELU_14_ACC_INT_BITS                                    16
#define CONVTRANSPOSE_RELU_14_ATILES                                          16
#define CONVTRANSPOSE_RELU_14_WTILES                                          1024
#define CONVTRANSPOSE_RELU_14_OFM_BITS                                        8
#define CONVTRANSPOSE_RELU_14_OFM_INT_BITS                                    1
#define CONVTRANSPOSE_RELU_14_OFM_BITS_ALIGNED                                8
#define CONVTRANSPOSE_RELU_14_OUTPUT_STREAM_WIDTH                             8
#define CONVTRANSPOSE_RELU_14_OUTPUT_MEM_WIDTH                                8
#define CONVTRANSPOSE_RELU_14_OUPUT_ACCESSESS                                 262144
typedef ap_fixed<CONVTRANSPOSE_RELU_14_IFM_BITS,CONVTRANSPOSE_RELU_14_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_14_input_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_14_WEIGHT_BITS,CONVTRANSPOSE_RELU_14_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_14_weight_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_14_BIAS_BITS,CONVTRANSPOSE_RELU_14_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_14_bias_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_14_ACC_BITS,CONVTRANSPOSE_RELU_14_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_14_acc_dtype;
typedef ap_fixed<CONVTRANSPOSE_RELU_14_OFM_BITS,CONVTRANSPOSE_RELU_14_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> convtranspose_relu_14_output_dtype;

#define CONCAT_2_IFM_CH                                                       16
#define CONCAT_2_IFM_DIM                                                      128
#define CONCAT_2_IFM_BITS                                                     8
#define CONCAT_2_IFM_INT_BITS                                                 1
#define CONCAT_2_OFM_BITS                                                     8
#define CONCAT_2_OFM_INT_BITS                                                 1
#define CONCAT_2_INPUT_STREAM_WIDTH                                           8
#define CONCAT_2_OFM_BITS_ALIGNED                                             8
#define CONCAT_2_OUTPUT_STREAM_WIDTH                                          8
typedef ap_fixed<CONCAT_2_IFM_BITS,CONCAT_2_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_2_input_dtype;
typedef ap_fixed<CONCAT_2_OFM_BITS,CONCAT_2_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_2_output_dtype;
#define CONCAT_2_OUPUT_ACCESSESS                                              262144

#define CONV_BN_RELU_15_K                                                     3
#define CONV_BN_RELU_15_IFM_CH                                                32
#define CONV_BN_RELU_15_IFM_DIM                                               128
#define CONV_BN_RELU_15_OFM_CH                                                16
#define CONV_BN_RELU_15_OFM_DIM                                               128
#define CONV_BN_RELU_15_GROUPS                                                1
#define CONV_BN_RELU_15_STRIDE                                                1
#define CONV_BN_RELU_15_PADDING                                               1
#define CONV_BN_RELU_15_SIMD                                                  1
#define CONV_BN_RELU_15_PE                                                    1
#define CONV_BN_RELU_15_IFM_BITS                                              8
#define CONV_BN_RELU_15_IFM_INT_BITS                                          1
#define CONV_BN_RELU_15_IFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_15_INPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_15_INPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_15_INPUT_ACCESSESS                                       524288
#define CONV_BN_RELU_15_WEIGHT_BITS                                           8
#define CONV_BN_RELU_15_WEIGHT_INT_BITS                                       -3
#define CONV_BN_RELU_15_WEIGHT_SIMD_WIDTH                                     8
#define CONV_BN_RELU_15_WEIGHT_SIMD_PE_WIDTH                                  8
#define CONV_BN_RELU_15_BIAS_BITS                                             8
#define CONV_BN_RELU_15_BIAS_INT_BITS                                         -10
#define CONV_BN_RELU_15_ACC_BITS                                              32
#define CONV_BN_RELU_15_ACC_INT_BITS                                          16
#define CONV_BN_RELU_15_ATILES                                                16
#define CONV_BN_RELU_15_WTILES                                                4608
#define CONV_BN_RELU_15_SCALE_BITS                                            32
#define CONV_BN_RELU_15_SCALE_INT_BITS                                        16
#define CONV_BN_RELU_15_SHIFT_BITS                                            32
#define CONV_BN_RELU_15_SHIFT_INT_BITS                                        16
#define CONV_BN_RELU_15_NORM_ACC_BITS                                         32
#define CONV_BN_RELU_15_NORM_ACC_INT_BITS                                     16
#define CONV_BN_RELU_15_OFM_BITS                                              8
#define CONV_BN_RELU_15_OFM_INT_BITS                                          1
#define CONV_BN_RELU_15_OFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_15_OUTPUT_STREAM_WIDTH                                   8
#define CONV_BN_RELU_15_OUTPUT_MEM_WIDTH                                      8
#define CONV_BN_RELU_15_OUPUT_ACCESSESS                                       262144
typedef ap_fixed<CONV_BN_RELU_15_IFM_BITS,CONV_BN_RELU_15_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_input_dtype;
typedef ap_fixed<CONV_BN_RELU_15_WEIGHT_BITS,CONV_BN_RELU_15_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_15_BIAS_BITS,CONV_BN_RELU_15_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_15_ACC_BITS,CONV_BN_RELU_15_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_15_SCALE_BITS,CONV_BN_RELU_15_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_15_SHIFT_BITS,CONV_BN_RELU_15_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_15_NORM_ACC_BITS,CONV_BN_RELU_15_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_15_OFM_BITS,CONV_BN_RELU_15_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_15_output_dtype;

#define CONV_BN_RELU_16_K                                                     3
#define CONV_BN_RELU_16_IFM_CH                                                16
#define CONV_BN_RELU_16_IFM_DIM                                               128
#define CONV_BN_RELU_16_OFM_CH                                                16
#define CONV_BN_RELU_16_OFM_DIM                                               128
#define CONV_BN_RELU_16_GROUPS                                                1
#define CONV_BN_RELU_16_STRIDE                                                1
#define CONV_BN_RELU_16_PADDING                                               1
#define CONV_BN_RELU_16_SIMD                                                  1
#define CONV_BN_RELU_16_PE                                                    1
#define CONV_BN_RELU_16_IFM_BITS                                              8
#define CONV_BN_RELU_16_IFM_INT_BITS                                          1
#define CONV_BN_RELU_16_IFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_16_INPUT_STREAM_WIDTH                                    8
#define CONV_BN_RELU_16_INPUT_MEM_WIDTH                                       8
#define CONV_BN_RELU_16_INPUT_ACCESSESS                                       262144
#define CONV_BN_RELU_16_WEIGHT_BITS                                           8
#define CONV_BN_RELU_16_WEIGHT_INT_BITS                                       -2
#define CONV_BN_RELU_16_WEIGHT_SIMD_WIDTH                                     8
#define CONV_BN_RELU_16_WEIGHT_SIMD_PE_WIDTH                                  8
#define CONV_BN_RELU_16_BIAS_BITS                                             8
#define CONV_BN_RELU_16_BIAS_INT_BITS                                         -9
#define CONV_BN_RELU_16_ACC_BITS                                              32
#define CONV_BN_RELU_16_ACC_INT_BITS                                          16
#define CONV_BN_RELU_16_ATILES                                                16
#define CONV_BN_RELU_16_WTILES                                                2304
#define CONV_BN_RELU_16_SCALE_BITS                                            32
#define CONV_BN_RELU_16_SCALE_INT_BITS                                        16
#define CONV_BN_RELU_16_SHIFT_BITS                                            32
#define CONV_BN_RELU_16_SHIFT_INT_BITS                                        16
#define CONV_BN_RELU_16_NORM_ACC_BITS                                         32
#define CONV_BN_RELU_16_NORM_ACC_INT_BITS                                     16
#define CONV_BN_RELU_16_OFM_BITS                                              8
#define CONV_BN_RELU_16_OFM_INT_BITS                                          1
#define CONV_BN_RELU_16_OFM_BITS_ALIGNED                                      8
#define CONV_BN_RELU_16_OUTPUT_STREAM_WIDTH                                   8
#define CONV_BN_RELU_16_OUTPUT_MEM_WIDTH                                      8
#define CONV_BN_RELU_16_OUPUT_ACCESSESS                                       262144
typedef ap_fixed<CONV_BN_RELU_16_IFM_BITS,CONV_BN_RELU_16_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_input_dtype;
typedef ap_fixed<CONV_BN_RELU_16_WEIGHT_BITS,CONV_BN_RELU_16_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_weight_dtype;
typedef ap_fixed<CONV_BN_RELU_16_BIAS_BITS,CONV_BN_RELU_16_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_bias_dtype;
typedef ap_fixed<CONV_BN_RELU_16_ACC_BITS,CONV_BN_RELU_16_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_16_SCALE_BITS,CONV_BN_RELU_16_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_scale_dtype;
typedef ap_fixed<CONV_BN_RELU_16_SHIFT_BITS,CONV_BN_RELU_16_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_shift_dtype;
typedef ap_fixed<CONV_BN_RELU_16_NORM_ACC_BITS,CONV_BN_RELU_16_NORM_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_norm_acc_dtype;
typedef ap_fixed<CONV_BN_RELU_16_OFM_BITS,CONV_BN_RELU_16_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_bn_relu_16_output_dtype;

#define CONV_14_K                                                             1
#define CONV_14_IFM_CH                                                        16
#define CONV_14_IFM_DIM                                                       128
#define CONV_14_OFM_CH                                                        2
#define CONV_14_OFM_DIM                                                       128
#define CONV_14_GROUPS                                                        1
#define CONV_14_STRIDE                                                        1
#define CONV_14_PADDING                                                       0
#define CONV_14_SIMD                                                          1
#define CONV_14_PE                                                            1
#define CONV_14_IFM_BITS                                                      8
#define CONV_14_IFM_INT_BITS                                                  1
#define CONV_14_IFM_BITS_ALIGNED                                              8
#define CONV_14_INPUT_STREAM_WIDTH                                            8
#define CONV_14_INPUT_MEM_WIDTH                                               8
#define CONV_14_INPUT_ACCESSESS                                               262144
#define CONV_14_WEIGHT_BITS                                                   8
#define CONV_14_WEIGHT_INT_BITS                                               -1
#define CONV_14_WEIGHT_SIMD_WIDTH                                             8
#define CONV_14_WEIGHT_SIMD_PE_WIDTH                                          8
#define CONV_14_BIAS_BITS                                                     8
#define CONV_14_BIAS_INT_BITS                                                 -8
#define CONV_14_ACC_BITS                                                      32
#define CONV_14_ACC_INT_BITS                                                  16
#define CONV_14_ATILES                                                        2
#define CONV_14_WTILES                                                        32
#define CONV_14_OFM_BITS                                                      8
#define CONV_14_OFM_INT_BITS                                                  1
#define CONV_14_OFM_BITS_ALIGNED                                              8
#define CONV_14_OUTPUT_STREAM_WIDTH                                           8
#define CONV_14_OUTPUT_MEM_WIDTH                                              8
#define CONV_14_OUPUT_ACCESSESS                                               32768
typedef ap_fixed<CONV_14_IFM_BITS,CONV_14_IFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_14_input_dtype;
typedef ap_fixed<CONV_14_WEIGHT_BITS,CONV_14_WEIGHT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_14_weight_dtype;
typedef ap_fixed<CONV_14_BIAS_BITS,CONV_14_BIAS_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_14_bias_dtype;
typedef ap_fixed<CONV_14_ACC_BITS,CONV_14_ACC_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_14_acc_dtype;
typedef ap_fixed<CONV_14_OFM_BITS,CONV_14_OFM_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_14_output_dtype;

#define CONV_14_TOP_LEVEL_OUTPUT_BITS                                         8
#define CONV_14_TOP_LEVEL_OUTPUT_INT_BITS                                     1
typedef ap_fixed<CONV_14_TOP_LEVEL_OUTPUT_BITS,CONV_14_TOP_LEVEL_OUTPUT_INT_BITS,AP_RND_ZERO,AP_WRAP> conv_14_top_level_output_dtype;

#define Reps 1

#define MAX_OUTPUT_CLASSES 128000

#endif